### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by ThatOneCalculator** [richlewis42/electron-flask#4]
```fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/me/Downloads/electron-flask-master/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/me/Downloads/electron-flask-master/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/me/Downloads/electron-flask-master/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

happens whenever i run any of the `gulp` commands

**Comment by lewisacidic** [comment]
Hi! This is an old, quick and dirty project and I'm not familiar with the status of the dependencies anymore, and I'm afraid I don't have time to look deeply into the problem.

I might suspect this to be a version problem - are you using a globally installed `gulp`? If so, try using the version pinned in the package (3.9) instead.

**Comment by ThatOneCalculator** [comment]
Ok, I'll try that

**Comment by abulka** [comment]
I ran into this issue - seems [gulp 3 is broken with node 12](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node-js) and so you need to use node 11 instead, and use the gulp locally installed.

```
nvm use 11
npm install
node_modules/.bin/gulp electron
```
